#ifndef GUARD_CONSTANTS_HEX_ORB_H
#define GUARD_CONSTANTS_HEX_ORB_H

enum HexOrbResultCodes
{
    HEX_ORB_RESULT_FAIL_TYPE_0,
    HEX_ORB_RESULT_FAIL_TYPE_1,
    HEX_ORB_RESULT_FAIL_FAINTED,
    HEX_ORB_RESULT_FAIL_HAS_STATUS,
    HEX_ORB_RESULT_FAIL_ABILITY,
    HEX_ORB_RESULT_SUCCESS,
    HEX_ORB_RESULT_COUNT,
};

#endif // GUARD_CONSTANTS_HEX_ORB_H
